# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Chatter.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Chatter.Empty" do
  end
  add_message "Chatter.ChatMessage" do
    optional :sender, :string, 1
    optional :reciever, :string, 2
    optional :payload, :string, 3
  end
end

module Chatter
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("Chatter.Empty").msgclass
  ChatMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("Chatter.ChatMessage").msgclass
end
