# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Chatter.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Chatter.Empty" do
  end
  add_message "Chatter.PingRequest" do
    optional :from, :string, 1
  end
  add_message "Chatter.PingResponse" do
    optional :from, :string, 1
  end
  add_message "Chatter.ChatMessage" do
    optional :sender, :string, 1
    optional :reciever, :string, 2
    optional :payload, :string, 3
    optional :messagetype, :enum, 4, "Chatter.ChatMessage.MessageType"
  end
  add_enum "Chatter.ChatMessage.MessageType" do
    value :Message, 0
    value :InviteRequest, 1
  end
end

module Chatter
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("Chatter.Empty").msgclass
  PingRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("Chatter.PingRequest").msgclass
  PingResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("Chatter.PingResponse").msgclass
  ChatMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("Chatter.ChatMessage").msgclass
  ChatMessage::MessageType = Google::Protobuf::DescriptorPool.generated_pool.lookup("Chatter.ChatMessage.MessageType").enummodule
end
