# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: Chatter.proto for package 'Chatter'

require 'grpc'
require 'Chatter_pb'

module Chatter
  module ServerServices
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'Chatter.ServerServices'

      # Definition for the ping rpc on server-side
      rpc :Ping, Empty, Empty
      rpc :Echo, ChatMessage, ChatMessage
      rpc :nEcho, ChatMessage, stream(ChatMessage)
      rpc :PingPong, stream(ChatMessage), stream(ChatMessage)
    end

    Stub = Service.rpc_stub_class
  end
end
