# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: Chatter.proto for package 'Chatter'

require 'grpc'
require 'Chatter_pb'

module Chatter
  module ServerServices
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'Chatter.ServerServices'

      rpc :Ping, PingRequest, PingResponse
    end

    Stub = Service.rpc_stub_class
  end
  module ClientServices
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'Chatter.ClientServices'

      rpc :Ping, PingRequest, PingResponse
    end

    Stub = Service.rpc_stub_class
  end
end
